spring:
  cloud:
    gateway:
      globalcors:
#        统一配置跨域请求
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allow-credentials: true
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:9008/rsa/publicKey'

secure:
  ignore:
    urls: #配置白名单路径
      - "/auth/oauth/token"