server:
  port: 8084

spring:
  cloud:
    gateway:
      routes:
        - id: service-goods-route
          uri:  lb://service-goods
          predicates:
            - Path=/goods/**
        - id: service-order-route
          uri:  lb://service-order
          predicates:
            - Path=/order/**
  application:
    name: service-gateway


eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@
