server:
  port: 9000

eureka:
  instance:
    hostname: localhost
    #client发送给server心跳的频率
    lease-renewal-interval-in-seconds: 10
    #server收到下次心跳的超时时间，如果30秒还收不到，那你这个instance就拜拜，不和你玩了
    lease-expiration-duration-in-seconds: 30
  client:
    register-with-eureka: false #是否自己注册到注册中心
    fetch-registry: false #是否从eureka中获取注册信息
    service-url:        #配置参数给eureka client的请求地址
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/
  server:
    enable-self-preservation: false #关闭自我保护
    eviction-interval-timer-in-ms: 3000  #扫描失效服务的间隔时间,默认60秒，改30秒