server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否自己注册到注册中心
    fetch-registry: false #是否从eureka中获取注册信息
    service-url:        #配置参数给eureka client的请求地址
      defaultZone: http://${eureka.instance.hostname}:9000/eureka/